package com.routesense.domain.model;

import jakarta.persistence.*;

// Represents a record of a user's journey, including details like timestamp, duration, CO2 emissions, mode summary, destination, and transfers.
// This entity is stored in the "journey_records" table in the database.

@Entity
@Table(name = "journey_records")
public class JourneyRecord {

    // Primary key for the JourneyRecord entity, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private long timestamp;
    private String date;
    private int durationSeconds;
    private double co2Grams;
    private double carCo2Grams;
    private String modeSummary;
    private String destination;
    private int transfers;
    private String userId;

    protected JourneyRecord() {}

    // Constructor to create a new JourneyRecord with all necessary fields.
    public JourneyRecord(long timestamp, String date, int durationSeconds, double co2Grams, double carCo2Grams, String modeSummary, String destination, int transfers, String userId) {
        this.timestamp = timestamp;
        this.date = date;
        this.durationSeconds = durationSeconds;
        this.co2Grams = co2Grams;
        this.carCo2Grams = carCo2Grams;
        this.modeSummary = modeSummary;
        this.destination = destination;
        this.transfers = transfers;
        this.userId = userId;
    }

    // Getters for all fields to allow access to the JourneyRecord properties.
    public Long getId() { return id; }
    public long getTimestamp() { return timestamp; }
    public String getDate() { return date; }
    public int getDurationSeconds() { return durationSeconds; }
    public double getCo2Grams() { return co2Grams; }
    public double getCarCo2Grams() { return carCo2Grams; }
    public String getModeSummary() { return modeSummary; }
    public String getDestination() { return destination; }
    public int getTransfers() { return transfers; }
    public String getUserId() { return userId; }
}
